export enum Cuisine {
  NORTH_INDIAN = 'North Indian',
  SOUTH_INDIAN = 'South Indian',
  PUNJABI = 'Punjabi',
  GUJARATI = 'Gujarati',
  BENGALI = 'Bengali',
  MAHARASHTRIAN = 'Maharashtrian',
  RAJASTHANI = 'Rajasthani',
  CHINESE = 'Chinese',
  ITALIAN = 'Italian',
  CONTINENTAL = 'Continental',
  FAST_FOOD = 'Fast Food',
  BAKERY = 'Bakery',
}

export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  MERCHANT = 'MERCHANT',
  DELIVERY_PARTNER = 'DELIVERY_PARTNER',
  ADMIN = 'ADMIN',
}

export enum DeliveryPartnerApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum VehicleType {
  BICYCLE = 'BICYCLE',
  MOTORCYCLE = 'MOTORCYCLE',
  SCOOTER = 'SCOOTER',
  CAR = 'CAR',
}

export enum DeliveryDocumentType {
  DRIVING_LICENCE = 'DRIVING_LICENCE',
  IDENTITY_PROOF = 'IDENTITY_PROOF',
  VEHICLE_DOCUMENT = 'VEHICLE_DOCUMENT',
}

export enum DeliveryStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  ARRIVED_AT_MERCHANT = 'ARRIVED_AT_MERCHANT',
  PICKED_UP = 'PICKED_UP',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  ARRIVED_AT_CUSTOMER = 'ARRIVED_AT_CUSTOMER',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
  SUSPENDED = 'SUSPENDED',
}

export enum OtpPurpose {
  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  LOGIN = 'LOGIN',
  DELIVERY = 'DELIVERY',
}

export enum AddressLabel {
  HOME = 'HOME',
  WORK = 'WORK',
  OTHER = 'OTHER',
}
export enum RestaurantApprovalStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}
export enum RestaurantOpeningStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  TEMPORARILY_CLOSED = 'TEMPORARILY_CLOSED',
}
export enum DocumentType {
  FSSAI = 'FSSAI',
  PAN = 'PAN',
  GST = 'GST',
  BANK_PROOF = 'BANK_PROOF',
  IDENTITY_PROOF = 'IDENTITY_PROOF',
  OTHER = 'OTHER',
}
export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}
export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}
export enum FoodType {
  VEG = 'VEG',
  NON_VEG = 'NON_VEG',
  EGG = 'EGG',
}
export enum OrderStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  ASSIGNED = 'ASSIGNED',
  PICKED_UP = 'PICKED_UP',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}
export enum PaymentMethod {
  ONLINE = 'ONLINE',
  COD = 'COD',
}
export enum PaymentStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}
export enum PaymentProvider {
  RAZORPAY = 'RAZORPAY',
  CASH = 'CASH',
}
export enum DiscountType {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
}
export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}
export enum NotificationType {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  ORDER_PREPARING = 'ORDER_PREPARING',
  ORDER_READY = 'ORDER_READY',
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  DELIVERY_PICKED_UP = 'DELIVERY_PICKED_UP',
  DELIVERY_OTP = 'DELIVERY_OTP',
  ORDER_OUT_FOR_DELIVERY = 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  RESTAURANT_APPROVED = 'RESTAURANT_APPROVED',
  RESTAURANT_REJECTED = 'RESTAURANT_REJECTED',
}
export enum JobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
export enum WebhookStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}
export enum AuditAction {
  RESTAURANT_APPROVED = 'RESTAURANT_APPROVED',
  RESTAURANT_REJECTED = 'RESTAURANT_REJECTED',
  RESTAURANT_SUSPENDED = 'RESTAURANT_SUSPENDED',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_UNBLOCKED = 'USER_UNBLOCKED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  REFUND_CREATED = 'REFUND_CREATED',
  MENU_ITEM_DELETED = 'MENU_ITEM_DELETED',
}
export enum AuditEntityType {
  RESTAURANT = 'RESTAURANT',
  USER = 'USER',
  ORDER = 'ORDER',
  PAYMENT = 'PAYMENT',
  MENU_ITEM = 'MENU_ITEM',
}
export enum SortOrder {
  ASC = 'ASC',
  DESC = 'DESC',
}
export enum RestaurantSortField {
  CREATED_AT = 'createdAt',
  NAME = 'name',
  AVERAGE_RATING = 'averageRating',
}
export enum Environment {
  DEVELOPMENT = 'development',
  TEST = 'test',
  PRODUCTION = 'production',
}

export enum ErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  RESTAURANT_NOT_FOUND = 'RESTAURANT_NOT_FOUND',
  RESTAURANT_NOT_APPROVED = 'RESTAURANT_NOT_APPROVED',
  RESTAURANT_CLOSED = 'RESTAURANT_CLOSED',
  MENU_ITEM_NOT_FOUND = 'MENU_ITEM_NOT_FOUND',
  MENU_ITEM_UNAVAILABLE = 'MENU_ITEM_UNAVAILABLE',
  CART_EMPTY = 'CART_EMPTY',
  MULTIPLE_RESTAURANT_CART_NOT_ALLOWED = 'MULTIPLE_RESTAURANT_CART_NOT_ALLOWED',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  INVALID_ORDER_STATUS_TRANSITION = 'INVALID_ORDER_STATUS_TRANSITION',
  ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_VERIFICATION_FAILED = 'PAYMENT_VERIFICATION_FAILED',
  COUPON_INVALID = 'COUPON_INVALID',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  DELIVERY_LOCATION_OUT_OF_RANGE = 'DELIVERY_LOCATION_OUT_OF_RANGE',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED = 'OTP_ATTEMPTS_EXCEEDED',
  DELIVERY_PARTNER_NOT_APPROVED = 'DELIVERY_PARTNER_NOT_APPROVED',
  DELIVERY_NOT_AVAILABLE = 'DELIVERY_NOT_AVAILABLE',
  DELIVERY_ALREADY_ASSIGNED = 'DELIVERY_ALREADY_ASSIGNED',
}
